- name: Install Jenkins on web servers
  hosts: all 
  become: true 
  tasks:
    - name: install jenkins
      get_url: 
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: import jenkins keys
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
    
    - name: upgrade all packages
      yum:
        state: latest
        name: '*'
    
    - name: install java
      yum: 
        name: java-11-amazon-corretto-devel
        state: latest
    - name: install jenkins
      yum:
        name: jenkins

- name: start and enable jenkins
  hosts: all
  become: true
  tasks:
    - name: enable jenkins
      service:
        name: jenkins
        state: started
        enabled: true 

